version: '3.3'
services:
  database:
    image: postgres:latest
    container_name: valoriza_db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data/db:/var/lib/postgresql/data
  database_test:
    image: postgres:latest
    container_name: valoriza_db_test
    env_file:
      - ./.local.env
    ports:
      - "5433:5432"
    
